on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X 'POST' \
          'http://https://homeland-be.onrender.com/seeding' \
          -H 'accept: application/json' \
          -d ''
