name: Tests
on: 
  pull_request:
    branches: [test/main]
    types: [opened, synchronize, closed]          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Install modules
      run: npm ci
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        set -x

        docker version

        docker run --rm hello-world
        
        docker compose pull
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test
