name: Tests

on:
  pull_request:
    branches: [test/main]
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        node: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install modules
      run: npm i
  
      
    - name: Setup docker
      uses: douglascamata/setup-docker-macos-action@v1-alpha


      timeout-minutes: 12

    - name: Display Docker version
      run: docker version

    - name: Run hello-world in Docker
      run: docker run --rm hello-world

    - name: Pull and start Docker Compose
      run: |
        set -x
        
        docker compose pull
        docker compose up -d
        npx supabase start

    - name: Run tests
      timeout-minutes: 3
      run: |
        npm run test:cov --detectOpenHandles --u
        # npm run test:mutation -- --reporters progress,dashboard
